networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './certbot/www:/var/www/certbot/:ro'
      - './certs/certificate.crt:/etc/ssl/certs/certificate.crt:ro'
      - './certs/private.key:/etc/ssl/private/private.key:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    

  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev