networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './certbot/www:/var/www/certbot/:ro'
      - './certs:/etc/letsencrypt:ro'
    depends_on:
      - backend
      - frontend
      - certbot
    networks:
      - dev

  certbot:
    image: certbot/certbot
    volumes:
      - './certs:/etc/letsencrypt'
      - './certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d valdemir.ru -d www.valdemir.ru; sleep 12h & wait $${!}; done;'"
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev