name: CiCdApplication

on:
  push:
    branches:
     - main
    paths:
      - '.github/workflows/CiCdApplication.yaml'
      - 'lab3/CiCdApplication/**'
  pull_request:
    paths:
      - '.github/workflows/CiCdApplication.yaml'
      - 'lab3/CiCdApplication/**'
  workflow_dispatch:
  
jobs:
  build:  
    uses: ./.github/workflows/build-sample.yml
    with:
      name: CiCdApplication
      path: lab3/CiCdApplication
      module: app
    secrets:
      compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
      compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
      compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
