name: CiCdApplication

on:
  push:
    branches:
     - main
    paths:
      - '.github/workflows/CiCdApplication.yaml'
      - 'lab3/CiCdApplication/**'
  pull_request:
    paths:
      - '.github/workflows/CiCdApplication.yaml'
      - 'lab3/CiCdApplication/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check for README.md changes
        id: check_readme
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q 'lab3/CiCdApplication/README.md'; then
            echo "README.md was updated. Exiting."
            exit 0
          fi
          
      - name: Build CiCdApplication
        env:
          compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
          compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
          compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
          
        uses: ./.github/workflows/build-sample.yml
        with:
          name: CiCdApplication
          path: lab3/CiCdApplication
          module: app
