name: Scheduled Builds

on:
  push:
    branches:
     - main
  # schedule:
  #   - cron: '0 12 * * *' # Каждый день в 12:00

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build 
        working-directory: lab3/CiCdApplication
        run: ./gradlew build 
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: CiCdApplication.apk
          path: lab3/CiCdApplication/app/build/outputs/apk/debug/app-debug.apk
      - name: Notify Build Failed
        if: failure()
        run: echo "Build failed!"
