on:
  schedule:
    - cron: '0 3 * * *' # Каждый день в 3 утра

defaults:
  run: 
    working-directory: lab3/CiCdApplication
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Run tests
        run: ./gradlew test
